// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	DeleteAgent(ctx context.Context, id int64) (Agent, error)
	DeleteAuthor(ctx context.Context, id int64) (Author, error)
	DeleteBook(ctx context.Context, id int64) (Book, error)
	GetAgent(ctx context.Context, id int64) (Agent, error)
	GetAuthor(ctx context.Context, id int64) (Author, error)
	GetBook(ctx context.Context, id int64) (Book, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	ListAuthors(ctx context.Context) ([]Author, error)
	ListAuthorsByAgentID(ctx context.Context, agentID int64) ([]Author, error)
	ListAuthorsByBookID(ctx context.Context, bookID int64) ([]Author, error)
	ListBooks(ctx context.Context) ([]Book, error)
	ListBooksByAuthorID(ctx context.Context, authorID int64) ([]Book, error)
	SetBookAuthor(ctx context.Context, arg SetBookAuthorParams) error
	UnsetBookAuthors(ctx context.Context, bookID int64) error
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
}

var _ Querier = (*Queries)(nil)
